// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.0 (Build Build 614 04/24/2018)
// Created on Tue Dec 18 22:16:19 2018

CLOCK_DIV_50 CLOCK_DIV_50_inst
(
	.CLOCK_50MHz(CLOCK_50MHz_sig) ,	// input  CLOCK_50MHz_sig
	.CLOCK_1MHz(CLOCK_1MHz_sig) ,	// output  CLOCK_1MHz_sig
	.CLOCK_100KHz(CLOCK_100KHz_sig) ,	// output  CLOCK_100KHz_sig
	.CLOCK_10KHz(CLOCK_10KHz_sig) ,	// output  CLOCK_10KHz_sig
	.CLOCK_1KHz(CLOCK_1KHz_sig) ,	// output  CLOCK_1KHz_sig
	.CLOCK_100Hz(CLOCK_100Hz_sig) ,	// output  CLOCK_100Hz_sig
	.CLOCK_10Hz(CLOCK_10Hz_sig) ,	// output  CLOCK_10Hz_sig
	.CLOCK_1Hz(CLOCK_1Hz_sig) 	// output  CLOCK_1Hz_sig
);

